---
title: "Python Basics"
format: html
---
# Instructions

Welcome to your first project milestone!

In this project, you will use Python to investigate real data related to USAID's Journey to Self-Reliance (J2SR fact sheet: https://2017-2020.usaid.gov/sites/default/files/documents/1870/J2SR_Fact_Sheet_June_2020.pdf).

To learn more about the variables contained in the data sets,
refer to the data dictionaries for
[the J2SR data set](https://rstudio.github.io/academy-python-foreign-aid/assets/j2sr_dictionary.html)
and
[the D2R data set](https://rstudio.github.io/academy-python-foreign-aid/assets/d2r_dictionary.html).

We are interested in examining the impact of foreign aid on children's health across the globe. By the end of this project, we'd like to determine whether children's health has improved from 2014 to 2020 and which aid programs are most associated with the improvements. We'll split this project into milestones that build on each other to iteratively explore the data.

## How to complete a milestone

For each milestone, you will need to:

1. **Recreate a result,** like a plot, table, or model. This will require you to use the skills you have studied that week.

2. **Extend the result.** Explore a new question about the data--this will provide an opportunity to both apply the skills you learned that week and to teach yourself something new. We will provide suggestions each week, but you are encouraged to explore any aspect of the data that interests you. Alternatively, apply and extend the skills you learned that week by working with your own data.

Remember, being able to teach yourself new parts of a computer language is what will make you a truly competent open source programmer---and we are here to help.

You'll share your extension with your groupmates at the weekly meeting, and show them how they could do the same.

## The `j2sr` data set

The data contains information on individual countries' scores and overall average scores for various Journey to Self-Reliance metrics.

To learn more about the variables contained in the data set, refer to the data dictionary [here](https://rstudio.github.io/academy-python-foreign-aid/assets/j2sr_dictionary.html).

# Milestone

```{python}
#| label: 'setup'

# Import your packages here
import pandas as pd

# Set a display option so all columns of tables are displayed
pd.set_option('display.max_columns', None)
```

## Python Basics

In this milestone, you'll become familiar with the `j2sr` data set.

## Recreation

### Part 1

Let's start by loading the data that we'll be using:

- Run the setup chunk above, which will import pandas with the common alias, `pd`.
- Use `help(pd.read_csv)` to explore the help page for the pandas `read_csv()` function.
- Use `read_csv()` to load our data set, which is stored at `data/j2sr.csv`.
- Save the data set to a variable named `j2sr`.

Write your code in the following chunk:

```{python}
#| label: 'recreation_1'

```

### Part 2

Now that `j2sr` is loaded, run the following code chunk, which will pull out the `country`, `year`, and `gdp_per_capita_(ppp)` columns and save them as variables to use later.

```{python}
#| label: 'save_columns'

# This code may look unfamiliar.
# Don't worry, we will cover this in next week's tutorials.
country = j2sr['country']
year = j2sr['year']
gdp = j2sr['gdp_per_capita_(ppp)']
```

### Part 3

Use Python to explore our data:

- Display the contents of `j2sr`
- Display the contents of the columns that we saved separately for you: `country`, `year`, and `gdp`
- Use the built-in `min()` function to find the first year in `year`
- Use the built-in `max()` function to find the last year in `year`
- Use the pandas `Series.value_counts()` method to tally up the number of records for each `country` in the data set

*Hint:* you may want to look up the help pages for each of these functions.

Write your code in the following chunk:

```{python}
#| label: 'recreation_2'

```

## Extension

Explore `j2sr` in a new way. Consider using a new function, or something that you can learn from a help page.
Alternatively, try to learn more about the other variables in `j2sr`.
Keep in mind that next week's tutorials cover how to make plots.

**For your first extension, we encourage you to think small.** Throughout this course, you will build many skills to explore data; for this first week, your work will likely be fairly straightforward. Consider _limiting yourself to 30-45 minutes_ for this portion of your work; at the end of that time interval, stop working and make notes on your progress, dead-ends, and aspirations -- bringing those to your group for discussion during the milestone session.

Write your extension code in the following chunk:

```{python}
#| label: 'extension'

```
