---
title: "Summarize data"
format: html
---
# Instructions

This week, you learned about several more pandas methods.

You'll use these skills to summarize changes in child health over time by country.

To learn more about the variables contained in the data set,
refer to the data dictionary [here](https://rstudio.github.io/academy-python-foreign-aid/assets/j2sr_dictionary.html).

# Milestone

```{python}
#| label: 'setup'
#| include: false

# Import your packages here
import pandas as pd
from matplotlib import rcParams

# Set some options
pd.set_option('display.max_columns', None)
rcParams.update({'savefig.bbox': 'tight'}) # Keeps plotnine legend from being cut off

```

## Summarize data

In this milestone, you will summarize changes in child health over time by country.

## Recreation

### Part 1 - Import

Before you begin, you will need to import your data set.
Use the code chunk below to read the data from the data file `j2sr.csv`,
which is stored in the `data/` folder in your working directory.
Be sure to save the data set to a variable named `j2sr`.

```{python}
#| label: 'recreation_import'

```

### Part 2 - Summarize data for a single country

First, let's compute the change in child health between 2014 and 2020 for a single country: Bolivia. To do so, you will need to:

1. Subset the data to only include the years of interest (2014 and 2020)
2. Subset the data to only include the country of interest (Bolivia)
3. Calculate the change in child_health between 2014 and 2020

*Hint*: You may find the `.iloc[]` method helpful for this exercise. Remember that `iloc[]` is useful for selecting elements of a pd.Series or the rows of a pd.DataFrame based on their index location.

For example:

```{python}
#| label: 'iloc_example'

# select the first row of j2sr
first_row = j2sr.iloc[0]

# select the first row in the "country" column of j2sr
j2sr['country'].iloc[0]

# select the last row in the 'country' column of j2sr (indexing from the back)
j2sr['country'].iloc[-1]
```

Work in the chunk below. (Your result should be 0.069.)

```{python}
#| label: 'recreation-bolivia'

```

### Part 3 - Summarize data by country

Now, our goal is to transform `j2sr` into the following table by performing the computation above for **all** countries:

```{python}
#| label: 'recreate-this'
solution = pd.read_csv('data/milestone04.csv')
solution
```

To do so, you will need to do the following:

1. Subset the data to only include the years of interest (2014 and 2020)
2. Group the data by country
3. Calculate the change in child_health for each country in a new variable `child_health_change`

*Hints*:

* Use a call to `.groupby()` and `.apply()` in your solution. The call to `.apply()` should use a function that performs a computation very similar to the one you did in Part 2 above.
* The input to the function for `.groupby().apply()` should be a regular Series object (i.e., ungrouped)
* If needed, remember to `.reset_index()` and `.rename()` the column for the final data frame
* Note: the `j2sr` data set is already sorted in ascending order by year

Work in the code chunk below. Save the result as `health_change`.

```{python}
#| label: 'recreation-summary'

```

Run the following code chunk to test whether you have the same answer as the solution:

```{python}
#| label: 'compare'

# If your answer is correct, the comparison should return an empty DataFrame.
health_change.reset_index(drop=True).round(10).compare(solution.round(10))
```

## Extension

Use the code chunk(s) below to extend your work.
Try something that you can learn from experimentation, a help page, or a package website.

Consider:

1. Data visualization is often an easier way to see patterns than numbers in a table. Build a graph from your summary table. Which countries have the highest overall rates of change in child health?
2. How does change in child health vary by region or income group?
3. [any other research question of interest]

Alternately, working with a data set of your own, complete the following:

1. Read in your data
2. Use `.groupby()` and `.apply()` or `.agg()` to produce a summary table from your data
3. Create a related graph of this data subset using plotnine

```{python}
#| label: 'extension'

```
