---
title: "Data types"
format: html
---
# Instructions

This week, you learned about three data types in pandas -- strings, datetimes, and categoricals.

In this milestone, you will use a sorted categorical variable to visualize the top 25
total disbursements by country, in descending order.

To learn more about the variables contained in the data sets,
refer to the data dictionaries for
[the J2SR data set](https://rstudio.github.io/academy-python-foreign-aid/assets/j2sr_dictionary.html)
and
[the D2R data set](https://rstudio.github.io/academy-python-foreign-aid/assets/d2r_dictionary.html).

# Milestone

```{python}
#| label: 'setup'
#| include: false

# Import your packages here
import pandas as pd
from matplotlib import rcParams

# Set some options
pd.set_option('display.max_columns', None)
rcParams.update({'savefig.bbox': 'tight'}) # Keeps plotnine legend from being cut off
```

## Data types

In this milestone, you'll visualize the top 25 total disbursements by country in descending order.

## Recreation

### Part 1 - Import

Before you begin,
you will need to import your datasets.
Use the code chunk below to read two datasets from the `data/` directory:

1. `j2sr.csv`, save it as `j2sr`
2. `d2r.csv`, save it as `d2r`

```{python}
#| label: 'recreation-import'

```

### Part 2 - Prepare the data

Run the code chunk below to prepare the data.
It calculates the change in child health from 2014 to 2020 for each country (`health_change`),
as in the summarize milestone,
and the total aid disbursements from 2014 to 2020 for each country (`total_disbursements`).

```{python}
#| label: 'prep-data'

# change in child health from 2014 to 2020, for each country
health_change = (
  j2sr
  .loc[j2sr["year"].isin([2014, 2020])]
  .groupby("country")
  ["child_health"]
  .apply(lambda g: g.iloc[-1] - g.iloc[0])
  .reset_index()
  .rename(columns={"child_health": "child_health_change"})
)

# total disbursements from 2014 to 2020, for each country
total_disbursements = (
  d2r
  .loc[(d2r["result_name"] == "disbursements") & (d2r["fiscal_year"].isin(range(2014, 2021)))]
  .groupby("country_name")
  .agg({"disbursements": "sum"})
  .reset_index()
)
```

Now, run the following chunk to create a new data frame called `disbursement_top_25` that contains information about change in child health and total disbursements for the countries with the top 25 disbursements.

```{python}
#| label: 'top-25-disbursements'

# join the two tables, then keep the 25 countries with the largest total disbursements
disbursement_top_25 = (
  health_change
  .merge(total_disbursements, left_on="country", right_on="country_name")
  .nlargest(25, 'disbursements')
  .reset_index(drop=True)
)
```

### Part 3 - Visualize

Using the File Explorer on the left, navigate to the `images/` directory, then click on `milestone05a.png` to open an image in the Editor pane

Your task is to recreate this plot.

```{python}
#| label: 'recreation-visualize-1'

```

In this plot, the order of countries on the y axis is arbitrary (alphabetical).
We may want to order the countries in a more meaningful way before publishing the plot.

### Part 4 - Reorder categories

Using the File Explorer on the left, navigate to the `images/` directory, then click on `milestone05b.png` to open an image in the Editor pane

Your task is to recreate this new version of the plot.
Notice that the countries are now ordered by `disbursements`,
from largest to smallest.

We recommend that you:

1. Use `.sort_values()` to sort `disbursement_top_25`,
   based on the values in the `disbursements` column,
   to create a Series called `country_order` containing the associated names.

2. Use the values saved in `country_order` to add a sorted,
   Categorical column to `disbursement_top_25` called `country_cat`.
   _Hint:_ Use the function `pd.Categorical()`

3. Use the new `country_cat` column to recreate the plot.

```{python}
#| label: 'recreation-visualize-2'

```

## Extension

Using the code chunk below, investigate a research question about this data, using the skills you have learned this week and in previous weeks of Academy. Some ideas:

1. Which countries have the 25 *lowest* total disbursements? How does overall child health differ between countries with the highest and lowest disbursements?
2. Re-generate the summary tables above, this time incorporating information about both country and region. Then use faceting to incorporate information about region to your plots from the recreation -- do you notice any regional patterns?
3. Are disbursements to health-related sectors associated with larger changes in child health compared to disbursements to other types of sectors? Use string matching to wrangle the `d2r` data set in order to explore this question.
4. [any other research question of interest]

Alternately, working with a data set of your own, complete the following:

1. Read in your data
2. If your data set contains date, string, or categorical information, use a pandas function to correctly format and manipulate your variables.
3. Using a table or graph, present a meaningful subset of your modified data

```{python}
#| label: 'extension'

```
